FROM dbmi/etl-client:etl-client-i2b2tm-18.1

RUN git clone https://github.com/hms-dbmi/ETLToolSuite-MappingGenerator
RUN git clone https://github.com/hms-dbmi/ETLToolSuite-EntityGenerator
RUN git clone https://github.com/hms-dbmi/ETLToolSuite-WorkflowScripts
RUN git clone https://github.com/vianneyJouhet/ETL-dbGaP2PIC-SURE.git

RUN wget -P / https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.9.6-1/sratoolkit.2.9.6-1-ubuntu64.tar.gz -q
RUN tar -zxf sratoolkit.2.9.6-1-ubuntu64.tar.gz
RUN rm -rf sratoolkit.2.9.6-1-ubuntu64.tar.gz
RUN mv sratoolkit.2.9.6-1-ubuntu64/bin/* /usr/bin
RUN rm -rf sratoolkit.2.9.6-1-ubuntu64

COPY ./scripts /etl-workdir/scripts/
